[package]
name = "web"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures-util = "0.3.30"
gloo-console = "0.3.0"
gloo-net = { version = "0.5.0", features = ["http"] }
js-sys = "0.3.69"
shared = { path = "../shared" }
wasm-bindgen = "0.2.92"
wasm-streams = "0.4.0"
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3"
